# Generated by Django 5.2.4 on 2025-07-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_operation_app', '0003_alter_customuser_password_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(upload_to='Media/profile_images/'),
        ),
    ]
