# Generated by Django 5.2.4 on 2025-07-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_operation_app', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
    ]
